apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dotnet60-basic-jp71
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-vvlf-tenant/dotnet-component/devfile-sample-dotnet60-basic-jp71@sha256:321237c32e814c422a54a2e1939a66e0620388dbeb6319b36d10e79e9a26f427
        name: main
        resources: {}
status: {}
