apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-jp71
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-jp71
    app.kubernetes.io/part-of: dotnet-component
  name: devfile-sample-dotnet60-basic-jp71
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-jp71
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-jp71
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-vvlf-tenant/dotnet-component/devfile-sample-dotnet60-basic-jp71@sha256:321237c32e814c422a54a2e1939a66e0620388dbeb6319b36d10e79e9a26f427
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
